adjective_1 = input("Please enter a descriptive word (adjective): ")
adjective_2 = input("Please enter a descriptive word (adjective): ")
verb_1 = input("Please enter an action word (verb): ")
verb_2 = input("Please enter an action word (verb): ")
verb_ending_in_ing_1 = input("Please enter an action word ending in 'ing' (verb): ")
adverb_1 = input("Please enter an adverb (e.g. quickly, loudly): ")
noun_1 = input("Please enter a person, place, or thing (noun): ")
noun_2 = input("Please enter a person, place, or thing (noun): ")
noun_3 = input("Please enter a person, place, or thing (noun): ")
plural_noun_1 = input("Please enter a plural noun: ")
plural_noun_2 = input("Please enter a plural noun: ")
plural_noun_3 = input("Please enter a plural noun: ")
part_of_body_1 = input("Please enter a part of your body: ")
part_of_body_2 = input("Please enter a part of your body: ")
part_of_body_3 = input("Please enter a part of your body: ")

print("---------------------")
print("Story: Bicycle Riding")
print("---------------------")
print("Most doctors agree that bicycle", verb_ending_in_ing_1, "is an", adjective_1)
print("form of exercise that benefits", plural_noun_1, "of all ages.")
print("Riding a bicycle enables you to develop your", part_of_body_1, "muscles")
print("as well as", adverb_1, "increase the rate of your", part_of_body_2)
print("beat. Bicycle riding is also an", adjective_2, "means of", noun_1, ".")
print("More", plural_noun_2, "around the world", verb_1, "bicycles than")
print("drive", plural_noun_3, ". No matter what kind of", noun_2, "you ride,")
print("always be sure to wear a", noun_3, "on your head and have reflectors")
print("on your", part_of_body_3, ", especially if you", verb_2, "at night.")


