adjective_1   = input("Please enter a descriptive word (adjective): ")
adjective_2   = input("Please enter a descriptive word (adjective): ")
adjective_3   = input("Please enter a descriptive word (adjective): ")
adjective_4   = input("Please enter a descriptive word (adjective): ")
noun_1        = input("Please enter a person, place, or thing (noun): ")
noun_2        = input("Please enter a person, place, or thing (noun): ")
noun_3        = input("Please enter a person, place, or thing (noun): ")
plural_noun_1 = input("Please enter a plural noun: ")
nationality_1 = input("Please enter a nationality: ")
person_1      = input("Please enter a person's name: ")
number_1      = input("Please enter a number: ")
number_2      = input("Please enter a number: ")
shapes_1      = input("Please enter a shape (that ends in s): ")
food_1        = input("Please enter a food: ")
food_2        = input("Please enter a food: ")

print("----------------------")
print("Story: All About Pizza")
print("----------------------")
print("Pizza was invented by a", adjective_1, nationality_1, "chef named", person_1, ".")
print("To make a pizza, you need to take a lump of", noun_1, ", and make a thin, round,", adjective_2, noun_2, ".")
print("Then you cover it with", adjective_3, "sauce,", adjective_4, "cheese, and fresh chopped", plural_noun_1, ".")
print("Next you have to bake it in a very hot", noun_3, ".")
print("When it is done, cut it into", number_1, shapes_1, ".")
print("Some kids like", food_1, "pizza the best, but my favorite is the", food_2, "pizza.")
print("If I could, I would eat pizza", number_2, "times a day!")
