adjective_1 = input("Please enter a descriptive word (adjective): ")
adjective_2 = input("Please enter a descriptive word (adjective): ")
verb_1 = input("Please enter an action word (verb): ")
verb_ending_in_ing_1 = input("Please enter an action word ending in 'ing' (verb): ")
verb_ending_in_ing_2 = input("Please enter an action word ending in 'ing' (verb): ")
adverb_1 = input("Please enter an adverb (e.g. quickly, loudly): ")
noun_1 = input("Please enter a person, place, or thing (noun): ")
noun_2 = input("Please enter a person, place, or thing (noun): ")
noun_3 = input("Please enter a person, place, or thing (noun): ")
noun_4 = input("Please enter a person, place, or thing (noun): ")
plural_noun_1 = input("Please enter a plural noun: ")
person_you_know_1 = input("Please enter a person you know: ")
person_you_know_2 = input("Please enter a person you know: ")
number_1 = input("Please enter a number: ")
living_thing_1 = input("Please enter a living thing: ")
something_to_eat_1 = input("Please enter something to eat: ")

print("---------------------")
print("Story: Show and Tell")
print("---------------------")
print("Hello. My name is", person_you_know_1, ", and I would like")
print("to show everyone a", noun_1, "I caught when")
print("I went", verb_ending_in_ing_1, "with my aunt. I had never fished before,")
print("but my aunt", adverb_1, "taught me how to bait a hook with a", living_thing_1)
print("and then how to cast the", noun_2, "into the")
print(adjective_1, "lake. I", verb_1, "fishing!")
print("")
print("My name is", person_you_know_2, ", and I would like to show the")
print("class this", adjective_2, noun_3, "from my mother's kitchen.")
print("My mother uses it every morning to fix my", something_to_eat_1, ". It is")
print("also useful if you are into", verb_ending_in_ing_2, "or if you want to slice")
print("up some", plural_noun_1, ". If you want one, you can buy it at your")
print("local", noun_4, "store for only", number_1, "dollars.")


