adjective_1 = input("Please enter a descriptive word (adjective): ")
adjective_2 = input("Please enter a descriptive word (adjective): ")
verb_1 = input("Please enter a past tense action word (verb): ")
verb_2 = input("Please enter a past tense action word (verb): ")
verb_3 = input("Please enter a past tense action word (verb): ")
adverb_1 = input("Please enter an adverb (e.g. quickly, loudly): ")
noun_1 = input("Please enter a person, place, or thing (noun): ")
noun_2 = input("Please enter a person, place, or thing (noun): ")
plural_noun_1 = input("Please enter a plural noun: ")
plural_noun_2 = input("Please enter a plural noun: ")
plural_noun_3 = input("Please enter a plural noun: ")
type_of_liquid_1 = input("Please enter a type of liquid: ")

print("----------------------------")
print("Story: The Three Little Pigs")
print("----------------------------")
print("Once upon a time, there were three little pigs who decided to build")
print("themselves houses. The first pig was", adjective_1 , ", and he built")
print("his house out of", plural_noun_1 , ". The second pig worked very")
print(adverb_1, "and built a house out of", plural_noun_2 , ". But")
print("the third pig was", adjective_2 , ". He built his house out of")
print(plural_noun_3, " and", type_of_liquid_1 , ". Then one day a big wolf came")
print("along. When he saw the first pig's house, he", verb_1 , "and he")
print(verb_2, "until he blew it down. Then he blew down the second")
print("pig's", noun_1 , ". But no matter how hard he", verb_3 , ",")
print("he couldn't blow down the third pig's", noun_2 , ".")

